version: '3.8'

services:
  # Serviço da aplicação principal
  app:
    build: .
    image: speed-funnels:latest
    container_name: speed-funnels-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - META_APP_ID=${META_APP_ID}
      - META_APP_SECRET=${META_APP_SECRET}
      - META_REDIRECT_URI=${META_REDIRECT_URI}
      - JWT_SECRET=${JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedfunnels.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.speedfunnels.entrypoints=websecure"
      - "traefik.http.routers.speedfunnels.tls.certresolver=letsencrypt"
      - "traefik.http.services.speedfunnels.loadbalancer.server.port=3001"
    depends_on:
      - db
    networks:
      - speed-funnels-network
      - traefik-public

  # Serviço do banco de dados
  db:
    image: postgres:14-alpine
    container_name: speed-funnels-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - speed-funnels-network

  # Serviço Traefik como proxy reverso
  traefik:
    image: traefik:v2.9
    container_name: speed-funnels-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - traefik-acme:/etc/traefik/acme
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - ACME_EMAIL=${ACME_EMAIL}
      - TRAEFIK_USERNAME=${TRAEFIK_USERNAME}
      - TRAEFIK_PASSWORD_HASH=${TRAEFIK_PASSWORD_HASH}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_USERNAME}:${TRAEFIK_PASSWORD_HASH}"
    networks:
      - speed-funnels-network
      - traefik-public

networks:
  speed-funnels-network:
    driver: bridge
  traefik-public:
    external: true

volumes:
  postgres-data:
  traefik-acme:
