version: "3.7"

services:
  speed_funnels:
    image: marcussviniciusa/speed-funnels:v1.0.7
    restart: unless-stopped
    networks:
      - network_public
    environment:
      - NODE_ENV=production
      - DB_HOST=77.37.41.106
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Marcus1911!!Marcus
      - DB_NAME=speedfunnels
      - DB_SSL=false
      - SEQUELIZE_SSL=false
      - META_APP_ID=1082403447223274
      - META_APP_SECRET=2f7876d06426f849a51202150b3dd55a
      - META_REDIRECT_URI=https://speedfunnels.marcussviniciusa.cloud/auth/callback/facebook
      - GOOGLE_CLIENT_ID=vazio
      - GOOGLE_CLIENT_SECRET=vazio
      - GOOGLE_REDIRECT_URI=https://speedfunnels.marcussviniciusa.cloud/auth/callback/google
      - JWT_SECRET=aab33419d55426e0276078dd8b16eac990c163afab0f20645d976cd92c80eb96
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.speed_funnels.rule=Host(`speedfunnels.marcussviniciusa.cloud`)
        - traefik.http.routers.speed_funnels.entrypoints=websecure
        - traefik.http.routers.speed_funnels.tls=true
        - traefik.http.routers.speed_funnels.tls.certresolver=letsencryptresolver
        - traefik.http.services.speed_funnels.loadbalancer.server.port=3001

networks:
  network_public:
    external: true
    name: network_public
